docroot/sites/all/modules/features/basic_page/basic_page.features.field_instance.inc
docroot/sites/all/modules/features/featured_book/featured_book.features.field_instance.inc
docroot/sites/all/modules/features/forms/forms.features.field_instance.inc
docroot/sites/all/modules/features/ilr_workspan/ilr_workspan.features.field_instance.inc
docroot/sites/all/modules/features/news/news.features.field_instance.inc
docroot/sites/all/modules/features/promo/promo.features.field_instance.inc
docroot/sites/all/modules/features/registration_pages/registration_pages.features.field_instance.inc
docroot/sites/all/modules/features/scheinman_neutral/scheinman_neutral.features.field_instance.inc
docroot/sites/all/modules/features/spotlight/spotlight.features.field_instance.inc
docroot/sites/all/modules/features/student_portraits/student_portraits.features.field_instance.inc

https://www.pivotaltracker.com/story/show/85520494

update all field instance directory settings to per field directory

---

docroot/sites/all/modules/features/ilr_sdc_listings/ilr_sdc_listings.views_default.inc

https://www.pivotaltracker.com/story/show/86566194

change class table view to show both start and end dates

---

docroot/sites/all/modules/features/wit/wit.module
docroot/sites/all/modules/features/wit/wit.views_default.inc

Fix problem where unpublished wit articles weer included to determine last publish article date
function _wit_get_latest_pub_date was not setting "status" condition in entity field query
https://www.pivotaltracker.com/story/show/86146154

Wit Listing Fix

---

docroot/sites/all/modules/features/basic_page/basic_page.theme.inc

https://www.pivotaltracker.com/story/show/86796536

On file link display use extenstion instead of mime type

---

docroot/sites/all/modules/features/basic_page/basic_page.module

..https://www.pivotaltracker.com/story/show/85030380

Remove the ability to change tags of existing m..edia when embedding them

---

docroot/sites/all/modules/custom/elavon/elavon.module

Fixes bug in ilr_alumni_association_event_reg where manage display page was not working correctly

Fixed bug where elavon custom modules was altering wrong forms

---

docroot/sites/all/modules/features/ilr_sdc_listings/ilr_sdc_listings.module

https://www.pivotaltracker.com/story/show/87833256

SDC Class title on Course page

---

docroot/sites/all/modules/features/news/news.module
docroot/sites/all/modules/features/news/news.views_default.inc

https://www.pivotaltracker.com/story/show/86326076

Update New Archive to show all news paginated by default

---

docroot/sites/all/modules/features/ilr_sdc_listings/ilr_sdc_listings.views_default.inc
docroot/sites/all/themes/ilr_theme/scss/components/_courses_and_classes.scss

https://www.pivotaltracker.com/story/show/86915354

Updated Public Offerings View: Changed to table. Added 'Next Class' label

---

docroot/sites/all/modules/features/ilr_permissions/ilr_permissions.features.user_permission.inc

https://www.pivotaltracker.com/story/show/85948628

Updated ilr_permissions to Live site settings

---

docroot/sites/all/modules/features/forms/forms.module

Adds forms_entityform_view_alter hook to forms.module

Removes the phrase Submitted by Anonymous from entityform conf pg and email

---

docroot/sites/all/modules/features/forms/templates/scheinman-webcast-registration.tpl.php

This adds the tpl.php file for email, but NOT the featurized form or field bases.

Adds email tpl.php file for Scheinman webcast registration

---

docroot/sites/all/modules/custom/elavon/elavon.module
docroot/sites/all/modules/custom/forensics_payments/forensics_payments.info
docroot/sites/all/modules/custom/forensics_payments/forensics_payments.module
docroot/sites/all/modules/features/forms/templates/forensics-debate-camp-payment.tpl.php

This adds the tpl.php file for email, and updated elavon module, and new forensics_payments module, but NOT the featurized form or field bases.

Forensics2

---

docroot/sites/all/themes/ilr_theme/js/ilr_subnav.js

@daviddemello I'm pushing this up to dev for testing. The story is in Tracker.

Hides submenu when on top level pages without subpages

---

docroot/sites/all/modules/custom/elavon/elavon.module
docroot/sites/all/modules/custom/forensics_payments/forensics_payments.module
docroot/sites/all/modules/custom/ilr_alumni_events/ilr_alumni_events.module

@carolineHecht Please try this branch on your local system, and be sure to log out and clear browser cookies.

Elavon bug fixes

---

docroot/sites/all/modules/features/forms/forms.features.field_instance.inc
docroot/sites/all/modules/features/forms/forms.strongarm.inc
docroot/sites/all/modules/features/forms2/forms2.features.field_instance.inc
docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.features.field_instance.inc

Required recreating three features: forms, forms2, ilr_forms_students

Updates display settings for field collections and event dates

---

docroot/sites/all/modules/features/registration_pages/registration_pages.module

If multi-day, show start and end dates and don't show the time.

Improves display of event date for multi-day events

---

docroot/sites/all/modules/features/forms/templates/webcast-registration-ilr-online.tpl.php

Updates note about time zone in webcast confirmation email

---

docroot/sites/all/themes/ilr_theme/scss/components/_people_profile_thumb.scss
docroot/sites/all/themes/ilr_theme/scss/layout/_one_column.scss
docroot/sites/all/themes/ilr_theme/scss/style.scss

@daviddemello @fjp2cornell Believe it or not, these 3 changes drop the compiled css from nearly 800k to 320k, with no issues that I can find. Please take a look and let me know if this is good to merge.

Makes three small css refactors for big gains

---

docroot/sites/all/modules/features/forms/templates/scheinman-webcast-registration.tpl.php

The only change was that I deleted some lines from the email tpl file.

Updates email confirmation for Scheinman webcast registration

---

docroot/sites/all/themes/ilr_theme/scss/components/_ilr_at_70.scss

Aaron, I am wondering if the social-share-70th extend should be pulled out of the ilr-at-70 sass file and placed in the social sass file. Thoughts?

Initial commit. Fixes social icons for shared reflections

---

docroot/sites/all/themes/ilr_theme/scss/components/_ilr_at_70.scss
docroot/sites/all/themes/ilr_theme/scss/layout/_ilr-at-70-homepage-layout.scss

Want to keep the styles for .field-name-field-full-name in case a decision is made to show this element on the page again.

Hides name and repositions social icons on featured reflection

---

docroot/sites/all/modules/features/ilr_reflection/ilr_reflection.module
docroot/sites/all/modules/features/ilr_sdc_listings/ilr_sdc_listings.module

Just remembered to do the pull request for the reflection spam fix.

Reflection spam pipes fix

---

docroot/sites/all/themes/ilr_theme/scss/base/_typography.scss
docroot/sites/all/themes/ilr_theme/scss/components/_main_image.scss
docroot/sites/all/themes/ilr_theme/scss/components/_news_article.scss
docroot/sites/all/themes/ilr_theme/scss/components/_sidebar_second.scss
docroot/sites/all/themes/ilr_theme/scss/layout/_base.scss
docroot/sites/all/themes/ilr_theme/scss/style.scss

Initial step to adjust white space on the web site. There will probably be others as examples are found on the site.

White space issues

---

docroot/sites/all/modules/features/registration_pages/registration_pages.features.field_instance.inc
docroot/sites/all/modules/features/registration_pages/registration_pages.module

Updates registration form behavior for form availability

---

docroot/sites/all/modules/features/forms/forms.module

This is just the change to forms.module to handle custom params, no code in here to test it.

Updates forms emails to allow for custom params

---

docroot/sites/all/themes/ilr_theme/scss/components/_centered_blurb.scss
docroot/sites/all/themes/ilr_theme/scss/components/_homepage.scss
docroot/sites/all/themes/ilr_theme/scss/style.scss

Separates the centered blurb (mission statement) from the home page so it can be used throughout the site.

Centered blurb

---

docroot/sites/all/themes/ilr_theme/scss/components/_form_elements.scss

Need to fix this problem so we can add a form to the MPSNYC web site.

Fixes text input width problem, adds rounded corners to input fields

---

docroot/sites/all/modules/features/forms/forms.features.field_instance.inc

Updates classroom reservation form - help text on two fields

---

docroot/sites/all/modules/features/forms/forms.features.field_instance.inc
docroot/sites/all/modules/features/forms/forms.strongarm.inc
docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.features.field_instance.inc

Affected forms and ilr_forms_students features

Updates EMHRM and MILR Eligibility forms column headers for download

---

docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.features.field_instance.inc

Changes download for the three fex/wisp forms, feature is ilr_forms_students

Updates fex/wisp downloads to match Filemaker import better

---

docroot/sites/all/modules/features/forms/forms.features.field_instance.inc
docroot/sites/all/modules/features/forms/forms.features.inc
docroot/sites/all/modules/features/forms/forms.info
docroot/sites/all/modules/features/forms/forms.module
docroot/sites/all/modules/features/forms/forms.strongarm.inc
docroot/sites/all/modules/features/forms/templates/labor-roundtable-student-registr.tpl.php
docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.module

featuretest failed the first time, so I'm renaming the branch and trying again

Updates Labor Roundtable registration

---

docroot/sites/all/modules/features/forms2/forms2.features.field_instance.inc

Very tiny change, affects forms2 feature

Updates two field labels on Scheinman webcast reg

---

docroot/sites/all/modules/custom/ilr_alumni_events/ilr_alumni_events.js
docroot/sites/all/modules/custom/ilr_alumni_events/ilr_alumni_events.module
docroot/sites/all/modules/features/forms/forms.features.field_instance.inc
docroot/sites/all/modules/features/forms/forms.field_group.inc
docroot/sites/all/modules/features/forms/templates/ilr-alumni-association-event-reg.tpl.php
docroot/sites/all/modules/features/ilr_field_bases/ilr_field_bases.features.field_base.inc
docroot/sites/all/modules/features/ilr_field_bases/ilr_field_bases.info
docroot/sites/all/modules/features/registration_pages/registration_pages.features.conditional_fields.inc
docroot/sites/all/modules/features/registration_pages/registration_pages.features.field_instance.inc
docroot/sites/all/modules/features/registration_pages/registration_pages.info
docroot/sites/all/modules/features/registration_pages/registration_pages.strongarm.inc

Whole bunch of changes here for the hockey form:  Max number of tickets, get rid of non-member pricing.  Updates to 3 features - forms, ilr_field_bases, and registration_pages

Hockey oct2015

---

docroot/sites/all/themes/ilr_theme/scss/components/_subnav.scss

Initial commit. Fixes height problem for mobile nav

---

docroot/sites/all/themes/ilr_theme/scss/components/_highlighted_area.scss
docroot/sites/all/themes/ilr_theme/scss/style.scss

Promo design

---

docroot/sites/all/themes/ilr_theme/scss/components/_cemp.scss
docroot/sites/all/themes/ilr_theme/scss/components/_two_column_card.scss
docroot/sites/all/themes/ilr_theme/scss/style.scss

New layout for CEMP program calendar

Two columns

---

docroot/sites/all/themes/ilr_theme/scss/print.scss

Second version of print styles

Print styles v2

---

docroot/sites/all/modules/features/forms/forms.features.inc
docroot/sites/all/modules/features/forms/templates/webcast-registration-ilr-online.tpl.php

Removes technical info about webcast connection details.

Updates Webcast Registration confirmation web page and email text

---

docroot/sites/all/modules/features/ilr_paragraphs/ilr_paragraphs.module
docroot/sites/all/themes/ilr_theme/templates/field--paragraphs.tpl.php

to the individual paragraph items in a paragraph field.
So simple once you know how!

Adds paragraph bundle type class identifiers 

---

docroot/sites/all/modules/features/ilr_field_bases/ilr_field_bases.features.field_base.inc
docroot/sites/all/modules/features/ilr_field_bases/ilr_field_bases.info
docroot/sites/all/modules/features/ilr_paragraphs/ilr_paragraphs.features.field_instance.inc
docroot/sites/all/modules/features/ilr_paragraphs/ilr_paragraphs.field_group.inc
docroot/sites/all/modules/features/ilr_paragraphs/ilr_paragraphs.info
docroot/sites/all/modules/features/ilr_paragraphs/ilr_paragraphs.module
docroot/sites/all/themes/ilr_theme/scss/layout/_channel_page.scss

This is a pull request awaiting Nathan's testing for approval then deployment

Left right promos

---

docroot/sites/all/themes/ilr_theme/scss/layout/_channel_page.scss

Bug fix so not going to create the featuretest site.

Aligns youtube video input to the left on the reflections form

---

docroot/sites/all/themes/ilr_theme/scss/layout/_channel_page.scss

Can be merged, featuretest not needed

Fixes masonry layout for reflections at 768 break point

---

docroot/sites/all/modules/features/ilr_experience_reports/ilr_experience_reports.features.field_instance.inc
docroot/sites/all/modules/features/ilr_experience_reports/ilr_experience_reports.field_group.inc
docroot/sites/all/modules/features/ilr_experience_reports/ilr_experience_reports.info
docroot/sites/all/modules/features/ilr_experience_reports/ilr_experience_reports.module
docroot/sites/all/themes/ilr_theme/scss/components/_experience_report.scss

Renamed branch for review. Originally upd-exp-rpt-June2016

Upd exp rpt degree

---

docroot/sites/all/themes/ilr_theme/scss/components/_footer.scss
docroot/sites/all/themes/ilr_theme/scss/components/_social.scss
docroot/sites/all/themes/ilr_theme/scss/layout/_base.scss

Repositions social icons and google translate for mobile

---

docroot/sites/all/themes/ilr_theme/scss/components/_blog_post.scss

Testing on featuretest before merge

Displays blog posts on a basic page in a single column

---

docroot/sites/all/modules/features/forms/forms.module

VERY small change - just adds a few lines to the file forms.module.

Removes option to purchase zero tickets for alumni events

---

docroot/sites/all/themes/ilr_theme/scss/components/_mai.scss
docroot/sites/all/themes/ilr_theme/scss/components/_sidebar_second.scss

Removes white as default background for sidebar-second

---

docroot/sites/all/themes/ilr_theme/scss/components/_featured_profile.scss

Places degree and year on experience report when displayed in a list

---

docroot/sites/all/modules/features/ilr_field_bases/ilr_field_bases.features.field_base.inc
docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.features.field_instance.inc
docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.features.inc

Small changes, updates ilr_field_bases and ilr_student_forms

Updates Career Pathways form for 2016 event

---

docroot/sites/all/modules/features/forms/forms.features.field_instance.inc
docroot/sites/all/modules/features/forms/forms.info
docroot/sites/all/modules/features/forms/forms.install
docroot/sites/all/modules/features/forms/forms.strongarm.inc
docroot/sites/all/modules/features/ilr_field_bases/ilr_field_bases.features.field_base.inc
docroot/sites/all/modules/features/ilr_field_bases/ilr_field_bases.info

Deletes submissions and adds one field to the form

Labor rt sept2016

---

docroot/sites/all/modules/features/forms/forms.install
docroot/sites/all/modules/features/forms/forms.module

Needs updb (see forms.install) but no feature revert

Removes subm for eMediation form and removes one radio button option

---

docroot/sites/all/modules/custom/ilr_sub_sites/ilr_sub_sites.module
docroot/sites/all/themes/ilr_theme/scss/components/_subsite_header.scss
docroot/sites/all/themes/ilr_theme/scss/print.scss

This was a chore so doesn't need a featuretest site.

Adds WI brand to Men and Women as Allies subsite

---

docroot/sites/all/modules/features/ilr_certificate_programs/ilr_certificate_programs.js

Bug fix. Does not require featuretest site.

Properly positions CTA box on certificate programs when page loads

---

docroot/sites/all/themes/ilr_theme/scss/components/_course_search.scss
docroot/sites/all/themes/ilr_theme/scss/components/_form_elements.scss

Currently for review on featuretest

Form styles

---

docroot/sites/all/modules/features/ilr_certificate_programs/ilr_certificate_programs.module
docroot/sites/all/modules/features/ilr_sdc_listings/ilr_sdc_listings.module
docroot/sites/all/themes/ilr_theme/scss/base/_variables.scss
docroot/sites/all/themes/ilr_theme/scss/components/_certificate_info_aside.scss
docroot/sites/all/themes/ilr_theme/scss/components/_certificate_programs.scss

Currently for review on featuretest

Cert prog add price

---

docroot/sites/all/modules/features/forms/forms.install

Very simple, tested locally, doesn't need a featuretest site

Deletes entityform submissions from EMHRM check_your_eligibility form

---

docroot/sites/all/themes/ilr_theme/scss/components/_pb_display_a_block.scss

Adjusts layout for event and promo thumbnails on channel pages

---

docroot/sites/all/themes/ilr_theme/scss/components/_view_modes.scss

Keeps event heading font size the same for all break points

---

docroot/sites/all/modules/features/forms/templates/transfer-offer.tpl.php

Only changes the php.tpl file, no updb or fr required

Updates Transfer Option form email confirmation

---

docroot/sites/all/themes/ilr_theme/scss/components/_view_modes.scss

Card styles

---

docroot/sites/all/modules/features/forms/forms.install
docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.module

Only change is in forms.install, requires a "drush updb".

Deletes submissions from Peer Mentoring form

---

docroot/sites/all/themes/ilr_theme/scss/components/_campaign_cards.scss
docroot/sites/all/themes/ilr_theme/scss/style.scss

We be helpful if this could be reviewed on featuretest, or staging, if featuretest is not yet available.

Creates card styles with buttons to be used on landing pages

---

docroot/sites/all/themes/ilr_theme/scss/components/_sls.scss
docroot/sites/all/themes/ilr_theme/scss/layout/_sls_homepage_layout.scss

Style changes ready for review

Adjusts padding and adds hover states for SLS speakers

---

docroot/sites/all/modules/features/ilr_sdc_listings/ilr_sdc_listings.module

Removes cancelled classes from certificate program displays

Filters cancelled classes from certificate programs

---

.hooks
docroot/sites/all/modules/custom/featuretest/featuretest.drush.inc

Adds custom drush command for the profile on featuretest

---

docroot/sites/all/themes/ilr_theme/scss/components/_sls.scss
docroot/sites/all/themes/ilr_theme/scss/layout/_sls_homepage_layout.scss

Do not merge until it is confirmed that there will be a 7th moderator for SLS. If there will not be, this pull request can be deleted.

SLS styles for 7 moderators

---

docroot/sites/all/modules/custom/ilr_sub_sites/ilr_sub_sites.module
docroot/sites/all/themes/ilr_theme/images/logo-new-conversations.svg
docroot/sites/all/themes/ilr_theme/scss/components/_subsite_header.scss

This branch does not require a featuretest site. It can be deployed.

Adds site logo for New Conversations Project

---

docroot/sites/all/themes/ilr_theme/scss/components/_microsites.scss

To be reviewed on featuretest before deployment

Adds a video treatment for microsites

---

docroot/sites/all/modules/features/ilr_certificate_programs/ilr_certificate_programs.module
docroot/sites/all/modules/features/ilr_paragraphs/ilr_paragraphs.module
docroot/sites/all/modules/features/news/news.module

@daviddemello this fixes the bug that Joanne reported regarding the news article. I didn't have the time to go back and figure out how/when the cardinality changed for the field base definition, but that might be helpful to retrospect at some point.

Fixes bug with field_website_url cardinality change

---

docroot/sites/all/modules/contrib/focal_point/css/focal_point.css
docroot/sites/all/modules/contrib/focal_point/focal_point.admin.inc
docroot/sites/all/modules/contrib/focal_point/focal_point.api.php
docroot/sites/all/modules/contrib/focal_point/focal_point.effects.inc
docroot/sites/all/modules/contrib/focal_point/focal_point.info
docroot/sites/all/modules/contrib/focal_point/focal_point.install
docroot/sites/all/modules/contrib/focal_point/focal_point.module
docroot/sites/all/modules/contrib/focal_point/focal_point.smartcrop.inc
docroot/sites/all/modules/contrib/focal_point/focal_point.theme.inc
docroot/sites/all/modules/contrib/focal_point/js/focal_point.js
docroot/sites/all/modules/contrib/focal_point/test/FocalPointTest.php

Updates the focal point module because of a security vulnerability: https://www.drupal.org/sa-contrib-2019-015
I didn't test this at all, but the diff is a lot of comment and formatting fixes. Not too many substantive changes.

[Security] Update focal point module to version 1.2

---

docroot/sites/all/modules/custom/ilr_dev/ilr_dev.install
docroot/sites/all/modules/features/ilr_sdc_listings/ilr_sdc_listings.module

@jeffam could you take a look at these 2 commits and let me know your thoughts or suggestions for a better approach (particularly regarding the `hook_node_insert()` implementation. Thanks

Duplicate entry bug

---

docroot/sites/all/themes/ilr_theme/scss/components/_course_search.scss
docroot/sites/all/themes/ilr_theme/scss/components/_form_elements.scss

Fix for lack of input focus on a few form elements.

focus error fix

---

docroot/sites/all/themes/ilr_theme/scss/base/_headings.scss
docroot/sites/all/themes/ilr_theme/scss/base/_variables.scss
docroot/sites/all/themes/ilr_theme/scss/base/_view_mode-mixins.scss
docroot/sites/all/themes/ilr_theme/scss/components/_courses_and_classes.scss
docroot/sites/all/themes/ilr_theme/scss/components/_form_elements.scss
docroot/sites/all/themes/ilr_theme/scss/components/_media.scss
docroot/sites/all/themes/ilr_theme/scss/components/_people_profile.scss
docroot/sites/all/themes/ilr_theme/scss/components/_people_profile_thumb.scss
docroot/sites/all/themes/ilr_theme/scss/components/_reflections.scss
docroot/sites/all/themes/ilr_theme/scss/components/_tables.scss
docroot/sites/all/themes/ilr_theme/scss/layout/_subsites.scss

Updates to contrast for links on a slight gray background.

updates to contrast errors

---

docroot/sites/all/themes/ilr_theme/templates/node--basic-page--mega-menu-item.tpl.php
docroot/sites/all/themes/ilr_theme/templates/node--channel-page--mega-menu-item.tpl.php
docroot/sites/all/themes/ilr_theme/templates/node--instagram-post--teaser.tpl.php

Minor accessibility 1

---

docroot/sites/all/modules/features/forms/templates/high-road-fellowship-application.tpl.php
docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.features.field_instance.inc
docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.features.inc

Minor form changes. Please make sure ilr_forms_students feature is reverted on deploy. 
Hid the markup field with link to project descriptions pdf instead of deleting it because they might want it back.

Changes to high_road_fellowship_application form for 202 cycle

---

docroot/sites/all/modules/features/ilr_sdc_listings/ilr_sdc_listings.module
docroot/sites/all/modules/features/people_profiles/people_profiles.module
docroot/sites/all/themes/ilr_theme/scss/base/_headings.scss
docroot/sites/all/themes/ilr_theme/template.php
docroot/sites/all/themes/ilr_theme/templates/html.tpl.php
docroot/sites/all/themes/ilr_theme/templates/media-youtube-video.tpl.php
docroot/sites/all/themes/ilr_theme/templates/node--instagram-post--teaser.tpl.php
docroot/sites/all/themes/ilr_theme/templates/views-view-table.tpl.php

Please excuse the granularity of the commits. I just wanted to make it clear on what each change was for. Feel free to squash.

More accessibility fixes

---

docroot/sites/all/modules/custom/ilr_sub_sites/ilr_sub_sites.module

@jeffam Can you take a look? A test url would be `/buffalo/worker-institute`, which should return a 404. Thanks!

Fixes sub site wrapping within sub sites

---

docroot/sites/all/modules/features/forms/templates/alumni-assoc-board-interest.tpl.php
docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.features.field_instance.inc
docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.info
docroot/sites/all/modules/features/ilr_forms_students/ilr_forms_students.strongarm.inc

adds phone field to open house form and also sneaks in a minor edit to the email response to people who fill in the alumni association board self-nomination form.

Edit mps open house form

---

docroot/profiles/ilr/ilr.install
docroot/sites/all/modules/custom/entity_form_disabler/README.md
docroot/sites/all/modules/custom/entity_form_disabler/entity_form_disabler.info
docroot/sites/all/modules/custom/entity_form_disabler/entity_form_disabler.module

@daviddemello This is ready for your quick review. There's a readme file included with some usage instructions.

Entity form disabler
